/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.DAOProduto;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import controller.ControllerProduto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import model.ModelProduto;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author CGFEGF
 */
public class ViewEstoque extends javax.swing.JFrame {

    ModelProduto modelProduto = new ModelProduto();
    ControllerProduto controllerProduto = new ControllerProduto();
    DAOProduto dAOProduto = new DAOProduto();
    List<ModelProduto> listProduto = new ArrayList<>();
    ArrayList<ModelProduto> listaProduto = new ArrayList();
    String desc;

    /**
     * Creates new form ViewSaida
     */
    public ViewEstoque() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
        AutoCompleteDecorator.decorate(jCBSaidaProduto);
        jTFDataSaida.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCBSaidaProduto = new javax.swing.JComboBox();
        jbPesquisarProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTfCodigoSaida = new javax.swing.JTextField();
        jTfDescProdSaida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDataSaida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpSaidaProd = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSaida = new javax.swing.JTable();
        jTFValorProEntrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFResponsavelEntrada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDataCadEntrada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSQtdEntrada = new javax.swing.JSpinner();
        jBtBaixar = new javax.swing.JButton();
        jBtAtualizarEstoque = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGE 1.0 - Atualizar Estoque");

        jLabel1.setText("Produto:");

        jCBSaidaProduto.setMaximumRowCount(5);
        jCBSaidaProduto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCBSaidaProdutoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jbPesquisarProduto.setBackground(new java.awt.Color(204, 204, 204));
        jbPesquisarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbPesquisarProduto.setText("Pesquisar");
        jbPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Descrição Produto:");

        jTfCodigoSaida.setEditable(false);

        jTfDescProdSaida.setEditable(false);

        jLabel4.setText("Data/Saída:");

        jTFDataSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Qtd. Saída:");

        jSpSaidaProd.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jTblSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Dt. Cadastro", "ValorProd", "Qtd. Saída", "Dt. Saida", "Responsável", "Est. Atual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblSaida);
        if (jTblSaida.getColumnModel().getColumnCount() > 0) {
            jTblSaida.getColumnModel().getColumn(0).setMinWidth(80);
            jTblSaida.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTblSaida.getColumnModel().getColumn(0).setMaxWidth(80);
            jTblSaida.getColumnModel().getColumn(2).setResizable(false);
            jTblSaida.getColumnModel().getColumn(4).setResizable(false);
            jTblSaida.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTblSaida.getColumnModel().getColumn(5).setMinWidth(80);
            jTblSaida.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTblSaida.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jTFValorProEntrada.setEditable(false);
        jTFValorProEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFValorProEntradaActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor");

        jLabel7.setText("Estoque Atual:");

        jTFResponsavelEntrada.setEditable(false);

        jLabel8.setText("Responsável:");

        jTFDataCadEntrada.setEditable(false);

        jLabel9.setText("Data de Cadastro");

        jSQtdEntrada.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCBSaidaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfCodigoSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorProEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTfDescProdSaida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpSaidaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTFDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSQtdEntrada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTFResponsavelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDataCadEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBSaidaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodigoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfDescProdSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpSaidaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFValorProEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFResponsavelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDataCadEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );

        jBtBaixar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBtBaixar.setText("Atualizar");
        jBtBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBaixarActionPerformed(evt);
            }
        });

        jBtAtualizarEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtAtualizarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jBtAtualizarEstoque.setText("Salvar");
        jBtAtualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAtualizarEstoqueActionPerformed(evt);
            }
        });

        jBtLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jBtLimpar.setText("Limpar");
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        jBtSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/visão-diurna-28.png"))); // NOI18N
        jButton2.setText("Tabela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtBaixar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAtualizarEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtBaixar)
                        .addComponent(jBtAtualizarEstoque)
                        .addComponent(jBtLimpar)
                        .addComponent(jBtSair)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBaixarActionPerformed
        modelProduto = new ModelProduto();

        int linha = jTblSaida.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um produto.");
        } else {
            int codigo = (int) jTblSaida.getValueAt(linha, 0);//recebe linha e coluna, e converte para inteiro
            modelProduto = controllerProduto.getProdutoController(codigo);
            jTfCodigoSaida.setText(String.valueOf(modelProduto.getProId()));
            jTfDescProdSaida.setText(modelProduto.getProDescricao());
            jSpSaidaProd.setValue(modelProduto.getProQuantidadeSaida());
            jTFDataSaida.setText(modelProduto.getProDataSaida());
            jTFValorProEntrada.setText(String.valueOf(modelProduto.getProValor()));
            jSQtdEntrada.setValue(modelProduto.getProQuantidade());
        }
    }//GEN-LAST:event_jBtBaixarActionPerformed

    private void jCBSaidaProdutoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCBSaidaProdutoAncestorAdded
        modelProduto = new ModelProduto();
        listProduto = dAOProduto.getListaProdutoDAO();
        jCBSaidaProduto.removeAllItems();

        for (ModelProduto p : listProduto) {
            jCBSaidaProduto.addItem(p.getProDescricao());
        }


    }//GEN-LAST:event_jCBSaidaProdutoAncestorAdded

    private void jbPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarProdutoActionPerformed
        pesquisaDescricao();
    }//GEN-LAST:event_jbPesquisarProdutoActionPerformed

    private void jTFValorProEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFValorProEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFValorProEntradaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carregarProdutos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtAtualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAtualizarEstoqueActionPerformed
        modelProduto = new ModelProduto();
        int estRest;
        int qtdEnt = (int) jSQtdEntrada.getValue();
        int qtdSai = (int) jSpSaidaProd.getValue();

        if (jSpSaidaProd.getValue().equals("") || jSpSaidaProd.getValue() == null || jTFDataSaida.getText() == null || jTFDataSaida.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são de preenchimento obrigatórios", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        } else {
            modelProduto.setProId(Integer.parseInt(jTfCodigoSaida.getText()));
            modelProduto.setProDescricao(jTfDescProdSaida.getText().toUpperCase());
            {
                if (qtdEnt < qtdSai) {
                    JOptionPane.showMessageDialog(this, "Estoque Insuficiente");
                    return;
                } else {
                    modelProduto.setProQuantidadeSaida((int) jSpSaidaProd.getValue());
                    modelProduto.setProQuantidade((int) jSQtdEntrada.getValue());
                    estRest = qtdEnt - qtdSai;
                    modelProduto.setProDataSaida(jTFDataSaida.getText());
                    modelProduto.setProDataCad(jTFDataCadEntrada.getText());
                    modelProduto.setProValor(Double.parseDouble(jTFValorProEntrada.getText()));
                    modelProduto.setProResponsavel(jTFResponsavelEntrada.getText());
                    modelProduto.setProRestante(estRest);

                    controllerProduto.atualizarEstoqueController(modelProduto);
                    JOptionPane.showMessageDialog(this, "Atualização Realizada com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    carregarProdutos();
                    limparFormulario();
                }
            }

        }

    }//GEN-LAST:event_jBtAtualizarEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAtualizarEstoque;
    private javax.swing.JButton jBtBaixar;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBSaidaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSQtdEntrada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpSaidaProd;
    private javax.swing.JTextField jTFDataCadEntrada;
    private javax.swing.JTextField jTFDataSaida;
    private javax.swing.JTextField jTFResponsavelEntrada;
    private javax.swing.JTextField jTFValorProEntrada;
    private javax.swing.JTable jTblSaida;
    private javax.swing.JTextField jTfCodigoSaida;
    private javax.swing.JTextField jTfDescProdSaida;
    private javax.swing.JButton jbPesquisarProduto;
    // End of variables declaration//GEN-END:variables

    private void carregarProdutos() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        listProduto = controllerProduto.getListaProdutoController();
        //preencher a lista
        DefaultTableModel modelo = (DefaultTableModel) jTblSaida.getModel();//instacia uma tabela básica e recebe a tabela do sistema.
        modelo.setRowCount(0);//limpar a tabela.
        //preencher tabela
        for (int i = 0; i < listProduto.size(); i++) {
            modelo.addRow(new Object[]{
                listProduto.get(i).getProId(), //posição do i igual a 0
                listProduto.get(i).getProDescricao(), //posição do i igual a 0
                listProduto.get(i).getProDataCad(),
                listProduto.get(i).getProValor(),
                listProduto.get(i).getProQuantidadeSaida(),//posição do i igual a 0
                listProduto.get(i).getProDataSaida(),
                listProduto.get(i).getProResponsavel(),
                listProduto.get(i).getProQuantidade(), //posição do i igual a 0
            });

        }
    }

    private void limparFormulario() {
        jTFDataSaida.setText("");
        jSpSaidaProd.setValue(1);
        jTfCodigoSaida.setText("");
        jTfDescProdSaida.setText("");
        jCBSaidaProduto.setSelectedIndex(0);

    }

    private void carregarProd() {

        modelProduto = controllerProduto.getProdutoDescricaoController(desc);
        DefaultTableModel modelo = (DefaultTableModel) jTblSaida.getModel();//instacia uma tabela básica e recebe a tabela do sistema.
        modelo.setRowCount(0);//limpar a tabela.
        modelo.addRow(new String[modelo.getRowCount()]);

        //preencher tabela
        for (int i = 0; i < listaProduto.size(); i++) {
//            jTblSaida.setValueAt(modelProduto.getProId(), i, 0);
//            jTblSaida.setValueAt(modelProduto.getProDescricao(), i, 1);
//            jTblSaida.setValueAt(modelProduto.getProQuantidadeSaida(), i, 2);
//            jTblSaida.setValueAt(modelProduto.getProDataSaida(), i, 3);

            modelo.addRow(new Object[]{
                listaProduto.get(i).getProId(), //posição do i igual a 0
                listaProduto.get(i).getProDescricao(), //posição do i igual a 0
                listaProduto.get(i).getProQuantidade(), //posição do i igual a 0
                listaProduto.get(i).getProValor(),//posição do i igual a 0
            // listaProduto.get(i).getProDtCad() //posição do i igual a 0
            });
        }
        System.out.println(modelProduto);
    }

    private void pesquisaDescricao() {
        desc = String.valueOf(jCBSaidaProduto.getSelectedItem());
        modelProduto.setProDescricao(desc);
        modelProduto = controllerProduto.getProdutoDescricaoController(desc);
        for (ModelProduto modelProduto1 : listProduto) {
            DefaultTableModel model = (DefaultTableModel) jTblSaida.getModel();
            model.setRowCount(0);// limpar a tabela

            model.addRow(new Object[]{
                modelProduto.getProId(), // posição de i igual a 0 
                modelProduto.getProDescricao(),
                modelProduto.getProDataCad(),
                modelProduto.getProValor(),
                modelProduto.getProQuantidadeSaida(),
                modelProduto.getProDataSaida(),
                modelProduto.getProResponsavel(),
                modelProduto.getProQuantidade()
            });

        }

    }

    public void gerarRelatorio() {
        modelProduto = new ModelProduto();
        Document doc = new Document(PageSize.A4.rotate(), 5f, 5f, 30f, 20f);

        listProduto = dAOProduto.getListaProdutoDAO();

        String arquivoPDF = "relatorioEstoque.pdf";
        try {
            
            PdfWriter.getInstance(doc, new FileOutputStream(arquivoPDF));
            doc.open();

            Font f = new Font(Font.FontFamily.UNDEFINED, 25, Font.BOLD);
            Paragraph p = new Paragraph("Relatório Estoque", f);
            p.setAlignment(1);
            doc.add(p);
            p = new Paragraph("");
            doc.add(p);
            float[] colsWidth = {0.8f, 8f, 2f, 2f, 2f, 2f};
            PdfPTable table = new PdfPTable(colsWidth);

            PdfPCell cel1 = new PdfPCell(new Paragraph("Cód"));
            PdfPCell cel2 = new PdfPCell(new Paragraph("Descrição"));
            PdfPCell cel3 = new PdfPCell(new Paragraph("Dt. Cadastro"));
            PdfPCell cel4 = new PdfPCell(new Paragraph("Qtd. Saída"));
            PdfPCell cel5 = new PdfPCell(new Paragraph("Dt. Saída"));
            PdfPCell cel6 = new PdfPCell(new Paragraph("Estoque Atual"));

            table.addCell(cel1);
            table.addCell(cel2);
            table.addCell(cel3);
            table.addCell(cel4);
            table.addCell(cel5);
            table.addCell(cel6);

            for (ModelProduto mp : listProduto) {

                cel1 = new PdfPCell(new Paragraph(mp.getProId() + ""));
                cel2 = new PdfPCell(new Paragraph(mp.getProDescricao() + ""));
                cel3 = new PdfPCell(new Paragraph(mp.getProDataCad() + ""));
                cel4 = new PdfPCell(new Paragraph(mp.getProQuantidadeSaida() + ""));
                cel5 = new PdfPCell(new Paragraph(mp.getProDataSaida() + ""));
                cel6 = new PdfPCell(new Paragraph(mp.getProRestante() + ""));

                table.addCell(cel1);
                table.addCell(cel2);
                table.addCell(cel3);
                table.addCell(cel4);
                table.addCell(cel5);
                table.addCell(cel6);

            }
            
            doc.add(table);
            doc.close();
            Desktop.getDesktop().open(new File(arquivoPDF));
        } catch (Exception e) {
        }
    }

}
