/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerProduto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;
import util.Formatador;

/**
 *
 * @author CGFEGF
 */
public class ViewProduto extends javax.swing.JFrame {

    ModelProduto modelProduto = new ModelProduto();
    ControllerProduto controllerProduto = new ControllerProduto();
    List<ModelProduto> listProduto = new ArrayList<>();
    Formatador formatador = new Formatador();
    String cadAlt = "cad";

    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        carregarProdutos();
        jTFdata.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTfCodigo = new javax.swing.JTextField();
        jTfDescricaoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfValorProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBsalvarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProduto = new javax.swing.JTable();
        jBlimpar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jSpQuantidade = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTFdata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFResponsavel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código:");

        jTfCodigo.setEditable(false);

        jLabel2.setText("Descrição produto:");

        jLabel3.setText("Valor:");

        jBsalvarProduto.setBackground(new java.awt.Color(204, 204, 204));
        jBsalvarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBsalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jBsalvarProduto.setText("Salvar");
        jBsalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarProdutoActionPerformed(evt);
            }
        });

        jTblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição produto", "Quantidade", "Valor", "Data de Cadastro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblProduto);
        if (jTblProduto.getColumnModel().getColumnCount() > 0) {
            jTblProduto.getColumnModel().getColumn(0).setMinWidth(80);
            jTblProduto.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTblProduto.getColumnModel().getColumn(0).setMaxWidth(80);
            jTblProduto.getColumnModel().getColumn(2).setMinWidth(100);
            jTblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTblProduto.getColumnModel().getColumn(2).setMaxWidth(100);
            jTblProduto.getColumnModel().getColumn(3).setMinWidth(100);
            jTblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTblProduto.getColumnModel().getColumn(3).setMaxWidth(100);
            jTblProduto.getColumnModel().getColumn(4).setMinWidth(100);
            jTblProduto.getColumnModel().getColumn(4).setPreferredWidth(160);
            jTblProduto.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        jBlimpar.setBackground(new java.awt.Color(204, 204, 204));
        jBlimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jBlimpar.setText("Limpar");

        jBexcluir.setBackground(new java.awt.Color(204, 204, 204));
        jBexcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBalterar.setBackground(new java.awt.Color(204, 204, 204));
        jBalterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jSpQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setText("Quantidade: ");

        jLabel6.setText("Data/Cadastro");

        jLabel4.setText("Responsável: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jBsalvarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jTfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 331, Short.MAX_VALUE))
                                    .addComponent(jTfDescricaoProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(140, 140, 140))
                                    .addComponent(jTfValorProduto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFResponsavel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBlimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBexcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBalterar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBsalvarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBalterar)
                    .addComponent(jBexcluir)
                    .addComponent(jBlimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        int linha = jTblProduto.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um produto.");
        } else {
            int codigo = (int) jTblProduto.getValueAt(linha, 0);//recebe linha e coluna, e converte para inteiro
            if (controllerProduto.excluirProdutoController(codigo)) {
                carregarProdutos();
                limparFormulário();
                JOptionPane.showMessageDialog(this, "Produto Excluído com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excuir Usuário!");
            }

        }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBsalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarProdutoActionPerformed
        modelProduto = new ModelProduto();
        if (jTFdata.getText().trim().equals("") || jTfDescricaoProduto.getText() == null || jTfDescricaoProduto.getText().trim().equals("")
        || jTFdata.getText() == null || jTFdata.getText().trim().equals("") || jSpQuantidade.getValue() == null || jSpQuantidade.getValue().equals("") ||
                JTFResponsavel.getText()==null || JTFResponsavel.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Todos os campos são de preenchimento obrigatórios", "Atenção", JOptionPane.INFORMATION_MESSAGE);

        } else {
            
            modelProduto.setProDescricao(jTfDescricaoProduto.getText().toUpperCase());
            modelProduto.setProQuantidade((int) jSpQuantidade.getValue());
            modelProduto.setProValor(formatador.converterVirgulaParaPonto(jTfValorProduto.getText()));
            modelProduto.setProDataCad(jTFdata.getText());
            modelProduto.setProResponsavel(JTFResponsavel.getText().toUpperCase());
            if (cadAlt.equals("cad")) {
                if (controllerProduto.salvarProdutoController(modelProduto)) {
                    //Cadastrou
                    JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    //Limpar
                    carregarProdutos();
                    limparFormulário();
                } else {
                    //não cadastrou
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                modelProduto.setProId(Integer.parseInt(jTfCodigo.getText()));
                if (controllerProduto.atualizarProdutoController(modelProduto)) {
                    JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    limparFormulário();
                    carregarProdutos();
                    /*==================================================================================================================================================*/

                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar!", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            }

        }


    }//GEN-LAST:event_jBsalvarProdutoActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        //editar usuário através do ID retornado do banco.
        cadAlt = "alt";
        modelProduto = new ModelProduto();
        int linha = jTblProduto.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um produto.");

        } else {
            int codigo = (int) jTblProduto.getValueAt(linha, 0);//recebe linha e coluna, e converte para inteiro
            modelProduto = controllerProduto.getProdutoController(codigo);
            jTfCodigo.setText(String.valueOf(modelProduto.getProId()));
            jTfDescricaoProduto.setText(modelProduto.getProDescricao());
            jSpQuantidade.setValue(modelProduto.getProQuantidade());
            jTfValorProduto.setText(String.valueOf(modelProduto.getProValor()));
            jTFdata.setText(modelProduto.getProDataCad());
            JTFResponsavel.setText(modelProduto.getProResponsavel());
        }

    }//GEN-LAST:event_jBalterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFResponsavel;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JButton jBsalvarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpQuantidade;
    private javax.swing.JTextField jTFdata;
    private javax.swing.JTable jTblProduto;
    private javax.swing.JTextField jTfCodigo;
    private javax.swing.JTextField jTfDescricaoProduto;
    private javax.swing.JTextField jTfValorProduto;
    // End of variables declaration//GEN-END:variables

    private void limparFormulário() {
        jTfDescricaoProduto.setText("");
        jTfValorProduto.setText("");
        cadAlt = "cad";
    }

    private void carregarProdutos() {
        listProduto = controllerProduto.getListaProdutoController();//preencher a lista
        DefaultTableModel modelo = (DefaultTableModel) jTblProduto.getModel();//instacia uma tabela básica e recebe a tabela do sistema.
        modelo.setRowCount(0);//limpar a tabela.

        //preencher tabela
        for (int i = 0; i < listProduto.size(); i++) {
            modelo.addRow(new Object[]{
                listProduto.get(i).getProId(), //posição do i igual a 0
                listProduto.get(i).getProDescricao(), //posição do i igual a 0
                listProduto.get(i).getProQuantidade(),
                listProduto.get(i).getProValor(),//posição do i igual a 0
                listProduto.get(i).getProDataCad(),
                listProduto.get(i).getProDataSaida(),
                listProduto.get(i).getProQuantidadeSaida(),
                listProduto.get(i).getProRestante(),
                listProduto.get(i).getProResponsavel()
            });

        }
    }
}
