/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerUsuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUsuario;

/**
 *
 * @author CGFEGF
 *
 **/
public class ViewUsuario extends javax.swing.JFrame {

    ModelUsuario modelUsuario = new ModelUsuario();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    List<ModelUsuario> listUsuarios = new ArrayList<>();//Instaciar a nova lista.
    String cadAlt = "cad";

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        carregarUsuarios();//chamar o método no construtor da classe.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTfCodigoUsuario = new javax.swing.JTextField();
        jTfNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPfSenhaUsuario = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblUsuario = new javax.swing.JTable();
        jBsalvarUsuario = new javax.swing.JButton();
        jBlimparUsuario = new javax.swing.JButton();
        jBexcluirUsuario = new javax.swing.JButton();
        jBalterarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código:");

        jTfCodigoUsuario.setEditable(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        jTblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblUsuario);
        if (jTblUsuario.getColumnModel().getColumnCount() > 0) {
            jTblUsuario.getColumnModel().getColumn(0).setMinWidth(100);
            jTblUsuario.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTblUsuario.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jBsalvarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jBsalvarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBsalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jBsalvarUsuario.setText("Salvar");
        jBsalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarUsuarioActionPerformed(evt);
            }
        });

        jBlimparUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jBlimparUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBlimparUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jBlimparUsuario.setText("Limpar");
        jBlimparUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpar(evt);
            }
        });

        jBexcluirUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jBexcluirUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBexcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jBexcluirUsuario.setText("Excluir");
        jBexcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirUsuarioActionPerformed(evt);
            }
        });

        jBalterarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jBalterarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBalterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBalterarUsuario.setText("Alterar");
        jBalterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBsalvarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPfSenhaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBlimparUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBexcluirUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBalterarUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalvarUsuario)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlimparUsuario)
                    .addComponent(jBexcluirUsuario)
                    .addComponent(jBalterarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarUsuarioActionPerformed
        modelUsuario = new ModelUsuario();

        if (jTfNomeUsuario.getText() == null || jTfNomeUsuario.getText().trim().equals("") || jTfLogin.getText() == null || jTfLogin.getText().trim().equals("")
                || jPfSenhaUsuario.getPassword() == null || jPfSenhaUsuario.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Preenchimento dos campos obrigatórios!", "Atençao!", JOptionPane.WARNING_MESSAGE);
        } else {
            modelUsuario.setUsuNome(jTfNomeUsuario.getText());
            modelUsuario.setUsuLogin(jTfLogin.getText());
            modelUsuario.setUsuSenha(String.valueOf(jPfSenhaUsuario.getPassword()));

            if (cadAlt.equals("cad")) {
                if (controllerUsuario.salvarUsuarioController(modelUsuario)) {
                    //Cadastrou
                    JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    //Limpar
                    limparFormulário();
                    carregarUsuarios();
                } else {
                    //não cadastrou
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                modelUsuario.setUsuId(Integer.parseInt(jTfCodigoUsuario.getText()));
                if (controllerUsuario.atualizarUsuarioController(modelUsuario)) {
                    //Alterou
                    JOptionPane.showMessageDialog(this, "Usário atualizado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    //Limpar
                    limparFormulário();
                    carregarUsuarios();
                } else {
                    //Não alterou
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            }

        }

    }//GEN-LAST:event_jBsalvarUsuarioActionPerformed

    private void Limpar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpar
        limparFormulário();
    }//GEN-LAST:event_Limpar

    private void jBexcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirUsuarioActionPerformed
        int linha = jTblUsuario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um usuário.");
        } else {
            int codigo = (int) jTblUsuario.getValueAt(linha, 0);//recebe linha e coluna, e converte para inteiro
            if (controllerUsuario.excluirUsuarioController(codigo)) {
                carregarUsuarios();
                limparFormulário();
                JOptionPane.showMessageDialog(this, "Usuário Excluído com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excuir Usuário!");
            }

        }
    }//GEN-LAST:event_jBexcluirUsuarioActionPerformed

    private void jBalterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarUsuarioActionPerformed
        //editar usuário através do ID retornado do banco.
        cadAlt = "alt";
        modelUsuario = new ModelUsuario();
        int linha = jTblUsuario.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um usuário.");
        } else {
            int codigo = (int) jTblUsuario.getValueAt(linha, 0);//recebe linha e coluna, e converte para inteiro
            modelUsuario = controllerUsuario.getUsuarioController(codigo);
            jTfCodigoUsuario.setText(String.valueOf(modelUsuario.getUsuId()));
            jTfNomeUsuario.setText(modelUsuario.getUsuNome());
            jTfLogin.setText(modelUsuario.getUsuLogin());
            jPfSenhaUsuario.setText(modelUsuario.getUsuSenha());
        }
    }//GEN-LAST:event_jBalterarUsuarioActionPerformed

    //Limpar formulário de usuário
    private void limparFormulário() {//limpar formulálior usuário, private pois so essa classe usará o método.
        jTfCodigoUsuario.setText("");
        jTfNomeUsuario.setText("");
        jTfLogin.setText("");
        jPfSenhaUsuario.setText("");
        cadAlt = "cad";
    }

    /**
     * Carrega uma lista de usuários na tabela.
     */
    private void carregarUsuarios() {
        listUsuarios = controllerUsuario.getListaUsuariosController();//preencher a lista
        DefaultTableModel modelo = (DefaultTableModel) jTblUsuario.getModel();//instacia uma tabela básica e recebe a tabela do sistema.
        modelo.setRowCount(0);//limpar a tabela.

        //preencher tabela
        for (int i = 0; i < listUsuarios.size(); i++) {
            modelo.addRow(new Object[]{
                listUsuarios.get(i).getUsuId(), //posição do i igual a 0
                listUsuarios.get(i).getUsuNome(), //posição do i igual a 0
                listUsuarios.get(i).getUsuLogin() //posição do i igual a 0
            });

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterarUsuario;
    private javax.swing.JButton jBexcluirUsuario;
    private javax.swing.JButton jBlimparUsuario;
    private javax.swing.JButton jBsalvarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPfSenhaUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblUsuario;
    private javax.swing.JTextField jTfCodigoUsuario;
    private javax.swing.JTextField jTfLogin;
    private javax.swing.JTextField jTfNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
