/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author CGFEGF
 */
public class ViewPrincipal extends javax.swing.JFrame {
    ViewUsuario viewUser = new ViewUsuario();
    ViewProduto viewProdt = new ViewProduto();
    ViewEstoque viewEst = new ViewEstoque();
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBusuario = new javax.swing.JButton();
        jBproduto = new javax.swing.JButton();
        jBestoque = new javax.swing.JButton();
        jBsobre = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMarquivo = new javax.swing.JMenu();
        jMiEstoque = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(218, 218, 218));

        jBusuario.setBackground(new java.awt.Color(204, 204, 204));
        jBusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jBusuario.setText("Usuário");
        jBusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jBusuario);

        jBproduto.setBackground(new java.awt.Color(204, 204, 204));
        jBproduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jBproduto.setText("Produto");
        jBproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprodutoActionPerformed(evt);
            }
        });
        jPanel2.add(jBproduto);

        jBestoque.setBackground(new java.awt.Color(204, 204, 204));
        jBestoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBestoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        jBestoque.setText("Estoque");
        jBestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBestoqueActionPerformed(evt);
            }
        });
        jPanel2.add(jBestoque);

        jBsobre.setBackground(new java.awt.Color(204, 204, 204));
        jBsobre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBsobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobre.png"))); // NOI18N
        jBsobre.setText("Sobre");
        jBsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsobreActionPerformed(evt);
            }
        });
        jPanel2.add(jBsobre);

        jBsair.setBackground(new java.awt.Color(204, 204, 204));
        jBsair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        jPanel2.add(jBsair);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 398, Short.MAX_VALUE))
        );

        jMarquivo.setText("Arquivos");

        jMiEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiEstoque.setText("Usuário");
        jMarquivo.add(jMiEstoque);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Produto");
        jMarquivo.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Estoque");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMarquivo.add(jMenuItem3);
        jMarquivo.add(jSeparator1);

        jMiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMiSair.setText("Sair");
        jMarquivo.add(jMiSair);

        jMenuBar1.add(jMarquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jBusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBusuarioActionPerformed
       
        if (viewUser == null) {
            
        }
        viewUser.setVisible(true);
    }//GEN-LAST:event_jBusuarioActionPerformed

    private void jBsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsobreActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jBsairActionPerformed

    private void jBprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprodutoActionPerformed
        if (viewProdt == null) {
            
        }
        viewUser.setVisible(true);
    }//GEN-LAST:event_jBprodutoActionPerformed

    private void jBestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBestoqueActionPerformed
        if (viewEst == null) {
            
        }
        viewEst.setVisible(true);
    }//GEN-LAST:event_jBestoqueActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBestoque;
    private javax.swing.JButton jBproduto;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsobre;
    private javax.swing.JButton jBusuario;
    private javax.swing.JMenu jMarquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMiEstoque;
    private javax.swing.JMenuItem jMiSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
